# Porta padrão para MQTT
listener 1883
# Permitir conexões anônimas (sem autenticação)
allow_anonymous true

# Log para facilitar debug
log_type all
log_dest stdout

# Persistência de mensagens (retain)
persistence true
persistence_location /mosquitto/data/